name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  firebase_ui_firestore: ^1.6.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  go_router: 14.1.2
  intl: ^0.19.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  # the annotation package containing @riverpod
  riverpod_annotation: 2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  random_string: ^2.3.1
  flutter_lints: ^3.0.2
  # a tool for running code generators
  build_runner: ^2.4.10
  # the code generator
  riverpod_generator: 2.4.0
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 2.3.10
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.6.4


flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
