name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_ui_auth: ^1.1.15
  firebase_ui_firestore: ^1.2.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^1.1.6
  go_router: 6.2.0
  intl: ^0.17.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  # the annotation package containing @riverpod
  riverpod_annotation: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  random_string: ^2.3.1
  flutter_lints: ^2.0.1
  # a tool for running code generators
  build_runner: 2.3.0
  # the code generator
  riverpod_generator: 2.2.1
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 1.3.1
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
